---
title: "p8105_hw6_zz3168"
author: "Zixuan Zhang"
date: "2023-11-28"
output: github_document
---

```{r}
library(tidyverse)
library(modelr)
```

### Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

do the r regression

```{r}
boost_sample_r = 
  weather_df |> 
  bootstrap(n = 5000) |> 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)
  ) |> 
  select(-strap, -models) |> 
  unnest(results) |> 
  janitor::clean_names()

conf_r =
  boost_sample_r |> 
  summarize(
    c_lower = quantile(r_squared, 0.025),
    c_upper = quantile(r_squared, 0.975)
  ) |> 
    knitr::kable()
  
  

```


#Identify the 2.5% and 97.5% quantiles 
```{r}
boost_sample_b = 
  weather_df |> 
  bootstrap(n = 5000) |> 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin + prcp, data = .x)),
    results = map(models, broom::tidy)
  ) |> 
  select(-strap, -models) |> 
  unnest(results) |>
  select(id = `.id`, term, estimate) |> 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |> 
  janitor::clean_names() |> 
  rename(beta0 = intercept, beta1 = tmin, beta2 = prcp) |> 
  mutate(
    log_b1 = log(beta0 * beta1),
    log_b2 = log(beta1 * beta2)
  )


conf_beta0 = 
  boost_sample_b |> 
  summarize(
    c_lower = quantile(log_b1, 0.025),
    c_upper = quantile(log_b1, 0.975)
  ) |> 
 knitr::kable() 


conf_beta1 = 
  boost_sample_b |> 
  summarize(
    c_lower = quantile(log_b2, 0.025,na.rm = TRUE),
    c_upper = quantile(log_b2, 0.975,na.rm = TRUE)
  ) |> 
 knitr::kable() 

  
  
```

According to the result, The 2.5% and 97.5% quantiles of of log(beta 1*beta 2) is -8.86 and -4.60. The 2.5% and 97.5% quantiles of R squard is 0.89 and 0.94. 

# do the r plot

```{r}
boost_sample_r |> 
  ggplot(aes(x = r_squared)) +
  geom_density()+
  labs(
    title = "Estimated R-Squared's Distribution ",
    x = "Estimated R Squared",
    y = "Density"
  )

```

#do the plot for Beta
```{r}
boost_sample_b |> 
  select(log_b2) |> 
  ggplot(aes(x = log_b2)) + 
  geom_density() + 
  labs(
    title = "Estimated Beta Distribution",
    x = "Estimated Beta1 * Beta2",
    y = "Density"
  )

```
According to the plot , we could see that the plot for R suqard is approximately normal, and the plot for  log(beta 1*beta 2) is skewed to the left.
 
### Problem 3

##clean and tidy the data
```{r}
birthwt_df = 
  read_csv("./data/birthweight.csv") |> 
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    mrace = as.factor(mrace),
    malform = as.factor(malform)
  ) |> 
  janitor::clean_names()


  
```

```{r}

```

